### ISSUE TITLE
adding recipes to local database from api call

### ISSUE THREAD

**Issue by awang2330** [reci-plan/capstone#10]
As a worker, I want to access a list of recipes on the site.

- [ ] If good response from Spoonacular:
          - [ ] Complete when all_recipes is loaded with desired data.
         
- [ ] Else
          - [ ] Complete when all_recipes stores the spoonacular IDs along with recipes we'll use for the site.
          - [ ] Find another API to use

**Comment by mpadil18** [comment]
As a worker, I want to access a list of recipes on the site.

- [ ] If good response from Spoonacular:
          - [ ] Complete when all_recipes is loaded with desired data.
         
- [ ] Else
          - [ ] Complete when all_recipes stores the spoonacular IDs along with recipes we'll use for the site.
          - [ ] Find another API to use
