### ISSUE TITLE
 randomly generate a meal / meal plan

### ISSUE THREAD

**Issue by awang2330** [reci-plan/capstone#7]
As a worker, I want to see a list of recipes categorized by difficulty, expense, and type, so I can search for the ones that align with my abilities and values.

- [x] Transfer selected categories from back to frontend `const data` for wheel component. Library does generation for us.
- [x] Complete when user can click on "add a meal"->selects time, meal name, and categories->click ok->popup closes and wheel updates->[SPIN] appears->spins and lands on id->popup with info about recipe landed on
- [x] User can save this meal option or close it

**Comment by mpadil18** [comment]
Potential library (good for many options on a wheel + good visuals): https://npm.io/package/react-custom-roulette

**Comment by mpadil18** [comment]
As a worker, I want to see a list of recipes categorized by difficulty, expense, and type, so I can search for the ones that align with my abilities and values.

- [ ] Transfer selected categories from back to frontend `const data` for wheel component. Library does generation for us.
- [ ] Complete when user can click on "add a meal"->selects time, meal name, and categories->click ok->popup closes and wheel updates->[SPIN] appears->spins and lands on id->popup with info about recipe landed on
- [ ] User can save this meal option or close it
